/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_patch_hebingAPK */

#ifndef _Included_com_example_patch_hebingAPK
#define _Included_com_example_patch_hebingAPK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_patch_hebingAPK
 * Method:    hbAPK
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_patch_hebingAPK_hbAPK
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
